sudo: required

services:
  - docker

before_install:
  - docker build -t rumi/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rumi/docker-react npm run test

after_success:
  - docker build -t manjurulhoque/client ./client
  - docker build -t manjurulhoque/nginx ./nginx
  - docker build -t manjurulhoque/server ./server
  - docker build -t manjurulhoque/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push manjurulhoque/client
  - docker push manjurulhoque/nginx
  - docker push manjurulhoque/server
  - docker push manjurulhoque/worker
